### PR TITLE
Dodge workers and pylint fixes

### PR DESCRIPTION
**Pull request by Matuiss2**
Still need testing, it will be useful only in very specific situations so its hard to test. If you can test it plz do

### CODE REVIEW

**Comment by Helfull** [comment]
i dont think that this will work, since it will be overwritten with the distribution.

**Comment by Matuiss2** [comment]
how to fix it you think?

**Comment by Helfull** [comment]
adding the dodge command after everything should overwrite other orders, which might do the trick, but might also could break the distribution.

**Comment by Matuiss2** [comment]
Maybe adding the if works? Like on the army_control, the problem I think it still has is that the workers would probably go back to that area to collect, after avoiding it

**Pull request merged**
